### PR TITLE
fixed tags overflowing in X axis

### PR DESCRIPTION
**Pull request by Elwafi-Elmehdi**
Hey @chrismwilliams 

I hope you are doing well,

I just found and fixed a small problem with posts with many tags

The page is overflowing on the X-axis and leading to horizontal scrolling.

I just added flex-wrap to  container styles and changed the position of the Tag SVG.

### CODE REVIEW

**Comment by Elwafi-Elmehdi** [comment]
I like to hear from you @chrismwilliams,

About Mermaid integration 

do you think it's stable enough to be integrated into the template or just on my blog?

**Comment by chrismwilliams** [comment]
Hi @Elwafi-Elmehdi thanks for doing this.

Yep I can see what you mean, I should probably add a couple of blog post's with edge cases to pick these things up. 

I've removed the span to fix the content stretching, and added some comma's for spacing so let me know if you can see anything else.

**Comment by chrismwilliams** [comment]
@Elwafi-Elmehdi regarding adding Mermaid, which I think you mean [this one](https://github.com/mermaid-js/mermaid), I must admit I've never used it, and if you have an example I'd like to see it if that's possible.

The only thing I can add is that I don't want to impose integrations that aren't core, whereby users would have to uninstall upon first using the template, if that makes sense.

Obviously if more people do ask for it I will do so, but what I can/could-do is add a section in the readme with links to other repo's that add additional features and showcase real-world examples.

Let me know what you think.

**Comment by Elwafi-Elmehdi** [comment]
I tested the changes in my template it looks good, I think it's all done here, Another feature that I think would be great is to add the Up button just like blogs, to navigate to the top of the page.

For the mermaid, Yes I think what you mentioned about examples will be great, the template should not be overloaded with integrations and should only be mentioned in the README file.

I will try it and see if it works because if the integration for Astro is still unstable, for the navigation button I think I can do my best to implement one and see it works.

**Pull request merged**
