### PR TITLE
Fix ThemeToggle component

### PR DESCRIPTION
**Pull request by atriple**
#### What kind of changes does this PR include?

- Minor fixes (broken links, typos, css, etc.)

#### Description

* Fix disappearing theme button when transitioning to different page. (In demo website, try to navigate Home <-> About page)
* Improve dark-light icons to load better by using dark modifier instead of aria-pressed attribute.

### CODE REVIEW

**Comment by chrismwilliams** [comment]
Hi @atriple thank you for taking the time to do this and bringing it to my attention, I hadn't noticed this was happening. 

The issue with the icon disappearing is an Astro bug involving persistence, and only after adding [named transitions](https://github.com/chrismwilliams/astro-theme-cactus/commit/6a207ea666ce3bdac01dce08741cb0850fd1e9bb) does the issue appear. 

For some reason the two unrelated elements break persistence set in the Header, hence why your fix works by having to continually set  `const button = ...` with every function invocation.

Until it's fixed, I've reverted the theme to not using View Transitions as this will trip people up in various instances, and left a message in the README to your request as a current solution.

Thanks again

**Comment by vedxp** [comment]
> Hi @atriple thank you for taking the time to do this and bringing it to my attention, I hadn't noticed this was happening.
> 
> The issue with the icon disappearing is an Astro bug involving persistence, and only after adding [named transitions](https://github.com/chrismwilliams/astro-theme-cactus/commit/6a207ea666ce3bdac01dce08741cb0850fd1e9bb) does the issue appear.
> 
> For some reason the two unrelated elements break persistence set in the Header, hence why your fix works by having to continually set `const button = ...` with every function invocation.
> 
> Until it's fixed, I've reverted the theme to not using View Transitions as this will trip people up in various instances, and left a message in the README to your request as a current solution.
> 
> Thanks again

We might use `transition:persist` directive on the Header component instead, for fixing the issue.

`src/components/layout/Header.astro`:
```html
<header
	id="main-header"
	class="group relative mb-28 flex items-center sm:ps-[4.5rem]"
	transition:persist
>
</header>
```

**Comment by chrismwilliams** [comment]
Thanks, and that's what I thought but unfortunately when this issue was created, [persist was included](https://github.com/chrismwilliams/astro-theme-cactus/blob/cab43cc0c2a87b0754028ab6f64a72821e3a859e/src/components/layout/Header.astro#L35). It worked until you then added a [named transition](https://github.com/chrismwilliams/astro-theme-cactus/blob/cab43cc0c2a87b0754028ab6f64a72821e3a859e/src/components/blog/PostPreview.astro#L21) on an unrelated element.

I've since changed the Toggle to a web component and removed the inline code, but it was those inconsistencies which meant that I just removed view-transitions as a default.

**Comment by vedxp** [comment]
> Thanks, and that's what I thought but unfortunately when this issue was created, [persist was included](https://github.com/chrismwilliams/astro-theme-cactus/blob/cab43cc0c2a87b0754028ab6f64a72821e3a859e/src/components/layout/Header.astro#L35). It worked until you then added a [named transition](https://github.com/chrismwilliams/astro-theme-cactus/blob/cab43cc0c2a87b0754028ab6f64a72821e3a859e/src/components/blog/PostPreview.astro#L21) on an unrelated element.
> 
> I've since changed the Toggle to a web component and removed the inline code, but it was those inconsistencies which meant that I just removed view-transitions as a default.

In that case, the latter approach works just fine. Thanks for clearing that up!

**Pull request closed without merging**
